Chatapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from personal.views import home_screen_view
from account.views import register_view, login_view, logout_view, account_search_view
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name='home'),
    path('register/', register_view, name = 'register'),
    path('login/', login_view, name = 'login'),
    path('logout/', logout_view, name = 'logout'),
    path('account/', include('account.urls', namespace = 'account')),
    path('chat/', include('chat.urls', namespace='chat')),
     path('search/', account_search_view, name = 'search'),
     path('friend/', include('friend.urls', namespace = 'friend')),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from account import views

app_name = "account"

urlpatterns = [
    path('<user_id>/', views.account_view, name = 'view'),
    path('<user_id>/edit/', views.edit_account_view, name = 'edit'),
    path('<user_id>/edit/cropImage/', views.crop_image, name = 'crop_image') 
]

chat/urls.py
from django.urls import path

from chat.views import(
	private_chat_room_view,
	create_or_return_private_chat,
)

app_name = 'chat'

urlpatterns = [
	path('', private_chat_room_view, name='private-chat-room'),
	path('create_or_return_private_chat/', create_or_return_private_chat, name='create-or-return-private-chat'),
]

templates/snippets/base_css.html
<style type="text/css">
    head{
        font-family: "Segoe UI";
        font-weight: 380;
    }

    footer{
        font-family: "Segoe UI";
        font-weight: 380;
    }

    body{
        font-family: "Segoe UI";
        font-weight: 380;
        background-color: #f2f2f2;
    }

    :root{
        --main-background-color: #f2f2f2;
        --dark-background-color: #a2a2a2;
        --secondary-text-color: #808080;
        --light-primary-text-color: #0080ff;
    }
</style>

templates/snippets/base_js.html
<script type="text/javascript">
	
	function preloadCallback(src, elementId){
		var img = document.getElementById(elementId)
		img.src = src
	}

	function preloadImage(imgSrc, elementId){
		// console.log("attempting to load " + imgSrc + " on element " + elementId)
		var objImagePreloader = new Image();
		objImagePreloader.src = imgSrc;
		if(objImagePreloader.complete){
			preloadCallback(objImagePreloader.src, elementId);
			objImagePreloader.onload = function(){};
		}
		else{
			objImagePreloader.onload = function() {
				preloadCallback(objImagePreloader.src, elementId);
				//    clear onLoad, IE behaves irratically with animated gifs otherwise
				objImagePreloader.onload=function(){};
			}
		}
	}

	/*
		Build a <p> for messages using markdown
		https://github.com/markdown-it/markdown-it
	*/
	function validateText(str)
	{
		var md = window.markdownit({
			highlight: function (str, lang) {
				if (lang && hljs.getLanguage(lang)) {
					try {
						return '<pre class="hljs"><code>' +
							hljs.highlight(lang, str, true).value +
							'</code></pre>';
					} catch (__) {}
				}
				return '<pre class="hljs"><code>' + md.utils.escapeHtml(str) + '</code></pre>';
			},
			linkify: true,
		});
		var result = md.render(str);
		return result
	}
	
</script>

templates/snippets/footer.html
<style type="text/css">
	.footer{
		min-height: 100px;
	}
</style>

<!-- Footer -->

<div class="d-flex flex-row align-items-center footer bg-white shadow-lg mt-4">
	<p class="m-auto">MikkyTechie Chat | 2023</p>
</div>

templates/snippets/header.html
{% load static %}

<style type="text/css">
	.chat-dropdown-header:hover{
		cursor: pointer;
		background: var(--main-background-color);
	}
	.chat-dropdown-header{
		color: var(--light-primary-text-color);
	}
	.scrollable-menu {
		height: auto;
		max-height: 90vh;
		width: 500px;
		overflow-x: hidden;
	}

	.notifications-material-icon {
		font-size: 28px;

	}
	.notifications-icon-container{
		width: 40px;
		height: 40px;
		background-color: var(--main-background-color);
	}
	.notifications-icon-container:hover {
		cursor: pointer;
		background-color: var(--secondary-text-color)
	}
	.notify-badge{
		position: absolute;
		background: transparent;
		height:1.2rem;
		width:1.2rem;
		line-height: 1.2rem;
		top:1rem;
		right:2rem;
		text-align: center;
		font-size: 1rem;
		border-radius: 50%;
		color:white;
		font-weight: 630;
		margin-top:-15px;
		margin-right: -25px;
	}
	#id_notifications_spinner{
		margin-top: 20px;
		margin-bottom: 20px;
	}
</style>

<!-- Header -->
<div class="d-flex flex-column flex-lg-row p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">

	<!-- MEDIUM+ SCREENS -->
	<div class="d-none d-md-flex flex-row my-auto flex-grow-1 align-items-center">
		<h5 class="mr-3 font-weight-normal justify-content-start">
			<a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
		</h5>
		<form class="search-bar justify-content-start" onsubmit="return executeQuery();">
			<input type="text" class="form-control" name="q" id="id_q_large" placeholder="Search...">
		</form>

		<div class="d-flex flex-row-reverse flex-grow-1">
			<nav class="">
				{% if request.user.is_authenticated %}
					<div class="dropdown dropleft show p-2">
						<div class="d-flex flex-row">

							<div class="btn-group dropleft">
								<div class="d-flex notifications-icon-container rounded-circle align-items-center mr-3" id="id_chat_notification_dropdown_toggle" data-toggle="dropdown">
									<span id="id_chat_notifications_count" class="notify-badge"></span>
									<span class="d-flex material-icons notifications-material-icon m-auto align-items-center">chat</span>
									<div class="dropdown-menu scrollable-menu" aria-labelledby="id_chat_notification_dropdown_toggle" id="id_chat_notifications_container">
									</div>
								</div>
							</div>

							<div class="btn-group dropleft">
								<div class="d-flex notifications-icon-container rounded-circle align-items-center mr-3" id="id_notification_dropdown_toggle" data-toggle="dropdown" onclick="setGeneralNotificationsAsRead()">
									<span id="id_general_notifications_count" class="notify-badge"></span>
									<span class="d-flex material-icons notifications-material-icon m-auto align-items-center">notifications</span>
									<div class="dropdown-menu scrollable-menu" aria-labelledby="id_notification_dropdown_toggle" id="id_general_notifications_container">					
									</div>
								</div>
							</div>

							<div class="btn-group dropleft">
								<img class="account-image rounded-circle m-auto d-block dropdown-toggle" id="id_profile_links" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="{{request.user.profile_image.url}}" alt="codingwithmitch logo" width="40" height="40">
								<div class="dropdown-menu" aria-labelledby="id_profile_links">
									<a class="dropdown-item" href="{% url 'account:view' user_id=request.user.id %}">Account</a>
									<a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
								</div>
							</div>
						</div>
						
					</div>
				{% else %}
					<a class="p-2 text-dark" href="{% url 'login' %}">Login</a>
					<a class="btn btn-outline-primary" href="{% url 'register' %}">Register</a>
				{% endif %}	
			</nav>
		</div>
	</div>
	<!-- END MEDIUM+ SCREENS -->

	<!-- SMALL SCREENS -->
	<div class="d-flex d-md-none flex-column my-auto align-items-center">
		<h5 class="font-weight-normal">
		<a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
		</h5>
		<form class="search-bar justify-content-start" onsubmit="return executeQuery();">
			<input type="text" class="form-control" name="q" id="id_q_small" placeholder="Search...">
		</form>
		<div class="d-flex flex-row-reverse flex-grow-1">
			<nav class="">
				{% if request.user.is_authenticated %}
				<div class="dropdown dropleft p-2 mt-2">
					<div class="d-flex flex-row">
						<div class="btn-group dropleft">
							<img class="account-image rounded-circle m-auto d-block dropdown-toggle" id="id_profile_links" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="{{request.user.profile_image.url}}" alt="codingwithmitch logo" width="40" height="40">
							<div class="dropdown-menu" aria-labelledby="id_profile_links">
								<a class="dropdown-item" href="{#% url 'account:view' request.user.id %#}">Account</a>
							</div>
						</div>
					</div>
				</div>
				{% else %}
					<a class="p-2 text-dark" href="{% url 'login' %}">Login</a>
					<a class="btn btn-outline-primary m-2" href="{% url 'register' %}">Register</a>
				{% endif %}	
			</nav>
	  	</div>
	</div>
	<!-- END SMALL SCREENS -->
</div>

{% include 'snippets/general_notifications.html' %}
{% include 'snippets/chat_notifications.html' %}
<script>
	// Correctly decide between ws:// and wss://
	var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
	var ws_path = ws_scheme + '://' + window.location.host + "/"; // development
	//var ws_path = ws_scheme + '://' + window.location.host + ":8001/public_chat/{{room_id}}/"; // production
	var notificationSocket = new WebSocket(ws_path);

	notificationSocket.onmessage = function(message){
		var data = JSON.parse(message.data);
		console.log("Got notification websocket message. " + data.general_msg_type);
		console.log("Got notification websocket message. " + data.chat_msg_type);
		
		/*
			GENERAL NOTIFICATIONS
		*/
		// new 'general' notifications data payload
		if(data.general_msg_type == 0){
			handleGeneralNotificationsData(data['notifications'], data['new_page_number'])
		}

		// Refresh [newest_timestamp >= NOTIFICATIONS >= oldest_timestamp]
		if(data.general_msg_type == 2){
			refreshGeneralNotificationsData(data['notifications'])
		}

		if(data.general_msg_type == 5){
			updateGeneralNotificationDiv(data['notification'])
		}

		if(data.general_msg_type == 3){
			handleNewGeneralNotificationsData(data['notifications'])
		}

		if(data.general_msg_type == 4){
			setUnreadGeneralNotificationsCount(data['count'])
		}

		// "General" Pagination exhausted. No more results.
		if(data.general_msg_type == 1){
			setGeneralPaginationExhausted()
		}

		/*
			CHAT NOTIFICATIONS
		*/
		// new 'chat' notifications data payload
		if(data.chat_msg_type == 10){
			handleChatNotificationsData(data['notifications'], data['new_page_number'])
		}

		// refreshed chat notifications
		if(data.chat_msg_type == 13){
			handleNewChatNotificationsData(data['notifications'])
		}
	}


	notificationSocket.onclose = function(e) {
		console.log('Notification Socket closed unexpectedly');
	};

	notificationSocket.onopen = function(e){
		console.log("Notification Socket on open: " + e)
		setupGeneralNotificationsMenu()
		getFirstGeneralNotificationsPage()
		getUnreadGeneralNotificationsCount()

		//setupChatNotificationsMenu()
		getFirstChatNotificationsPage()
	}

	notificationSocket.onerror = function(e){
		console.log('Notification Socket error', e)
	}

	if (notificationSocket.readyState == WebSocket.OPEN) {
		console.log("Notification Socket OPEN complete.")
	} 
	else if (notificationSocket.readyState == WebSocket.CONNECTING){
		console.log("Notification Socket connecting..")
	}
</script>

<script type="text/javascript">
	setupChatDropdownHeader();

	function executeQuery(){
		var query = document.getElementById("id_q_small").value
		if(query == ""){
			query = document.getElementById("id_q_large").value
		}
		window.location.replace("{% url 'search' %}?q=" + query)
		return false
	}

	function setupChatDropdownHeader(){
		var notificationContainer = document.getElementById("id_chat_notifications_container")

		if(notificationContainer != null){

			var div = document.createElement("div")
			div.classList.add("chat-dropdown-header", "d-flex", "flex-row", "justify-content-end", "m-auto", "align-items-end")
			div.addEventListener("click", function(e){
				var url = "{% url 'chat:private-chat-room' %}"
				chatRedirect(url)
			})

			span1 = document.createElement("span")
			span1.classList.add("mr-2")
			span1.innerHTML = "Go to chat"
			div.appendChild(span1)

			span2 = document.createElement("span")
			span2.classList.add("material-icons", "mr-2")
			span2.innerHTML = "open_with"
			div.appendChild(span2)
			notificationContainer.appendChild(div)
		}
	}

	function chatRedirect(url){
		window.location.href = url
	}
	
</script>